export const movieList = [
  {
    id: 1,
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    duration: 154,
    rating: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  },
  {
    id: 2,
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    duration: 132,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    duration: 152,
    rating: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  },
  {
    id: 4,
    title: "Forrest Gump",
    year: 1994,
    genre: "Drama",
    duration: 142,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
  },
  {
    id: 5,
    title: "Spirited Away",
    year: 2001,
    genre: "Animation",
    duration: 125,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  },
  {
    id: 6,
    title: "Gladiator",
    year: 2000,
    genre: "History",
    duration: 155,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  },
  {
    id: 7,
    title: "The Social Network",
    year: 2010,
    genre: "Biography",
    duration: 120,
    rating: 7.7,
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
  },
  {
    id: 8,
    title: "Avengers: Endgame",
    year: 2019,
    genre: "Superhero",
    duration: 181,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  },
  {
    id: 9,
    title: "The Conjuring",
    year: 2013,
    genre: "Horror",
    duration: 112,
    rating: 7.5,
    poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
  },
  {
    id: 10,
    title: "La La Land",
    year: 2016,
    genre: "Musical",
    duration: 128,
    rating: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  },
  {
    id: 11,
    title: "Joker",
    year: 2019,
    genre: "Psychological",
    duration: 122,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  },
  {
    id: 12,
    title: "Mad Max: Fury Road",
    year: 2015,
    genre: "Adventure",
    duration: 120,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
  },
  {
    id: 13,
    title: "The Shawshank Redemption",
    year: 1994,
    genre: "Drama",
    duration: 142,
    rating: 9.3,
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
  },
  {
    id: 14,
    title: "The Godfather",
    year: 1972,
    genre: "Crime",
    duration: 175,
    rating: 9.2,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
  },
  {
    id: 15,
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    duration: 148,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
  },
  {
    id: 16,
    title: "Fight Club",
    year: 1999,
    genre: "Drama",
    duration: 139,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
  },
];

export const selected_movie_list= [
  {
    id: 2,
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    duration: 132,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  },
  {
    id: 5,
    title: "Spirited Away",
    year: 2001,
    genre: "Animation",
    duration: 125,
    rating: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  },
  {
    id: 8,
    title: "Avengers: Endgame",
    year: 2019,
    genre: "Superhero",
    duration: 181,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  },
]